server:
  port: 8080

spring:
  application:
    name: CSC8019-backend
  datasource:
    url: jdbc:mysql://database-1.cnqwmw824u8a.eu-north-1.rds.amazonaws.com:3306/CSC8019?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: CSC8019!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: "myVerySecureAndSecretKeyForHS256AlgorithmWhichIsAtLeast32BytesLong"
  expiration: 604800000 # 7 days in milliseconds
